version: '3.8'

services:
  db:
    image: postgres:13
    container_name: pm_db
    environment:
      POSTGRES_USER: pm_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pm_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: